### ISSUE TITLE
Create Fig 1g

### ISSUE THREAD

**Issue by Puriney** [GreenleafLab/ArchR_2020#5]
Hello Ryan and Jeffrey,
This is Yun Yan. I was wondering if you could share the scripts to create the master VCF file of the mixed cell lines, as you showed in Fig 1g. I did not find it here so I create this issue to seek help.

I guess the method is described in the section "scATAC-seq processing: cell line mixing", if I am correct, but I was afraid I still cannot follow. What I understand so far is that each cell line's VCF is derived from its own bulk ATAC-seq data. But I still have many detailed questions. For example, why 'SAMtools mpileup' was run twice? 

If you could share the script with me (yyan7@mdanderson.org), it would be great so that I can figure it out. Many thanks.

**Comment by rcorces** [comment]
This is not a straightforward procedure and requires a lot of customization which is why the code was not included in the publication repository. The code was designed to run on our cluster with Slurm job submission and requires bulk ATAC-seq data as input. You can get an idea for what is being done by looking at the code but we provide it as is without additional support.

You can download the code here:
https://www.dropbox.com/s/fuiozp1utj9ljya/Demuxlet_Pipeline-master.zip?dl=0

**Comment by Puriney** [comment]
Thank you for the prompt reply. It is well documented. Should work for me.
